-- -- TABLE RELATED TO USERS ---
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL
);

-- -- TABLE RELATED TO SESSIONS ---
DROP TABLE IF EXISTS sessions;

CREATE TABLE sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  token TEXT NOT NULL,
  user_id INTEGER NOT NULL
);

-- TABLE RELATED TO ARTICLES ---
DROP TABLE IF EXISTS articles;

CREATE TABLE articles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  body INTEGER NOT NULL,
  creation_date TEXT NOT NULL,
  user_id INTEGER NOT NULL
);

-- TABLE RELATED TO COMMENTS ---
DROP TABLE IF EXISTS comments;

CREATE TABLE comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  message TEXT NOT NULL,
  creation_date TEXT NOT NULL,
  article_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL
);



